version: "3"

services:
    web:
        build: ./web
        ports:
            - "3000:80"
    api:
        build: ./api
        environment:
            - "PORT=8080"
        ports:
            - "8080:8080"
